ALTER TYPE "public"."rock_type" ADD VALUE 'granite_weathered';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'anorthosite';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'syenite_porous';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'rhyolite';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'tuff_welded';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'tuff_nonwelded';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'volcanic_breccia';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'quartzite';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'slate';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'gneiss_schist';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'sandstone_quartz_arenite';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'sandstone_ferruginous';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'sandstone_arkose';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'sandstone_eolian';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'sandstone_soft';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'limestone_dense';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'limestone_porous';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'dolomite';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'carbonate_cherty';--> statement-breakpoint
ALTER TYPE "public"."rock_type" ADD VALUE 'conglomerate';--> statement-breakpoint
ALTER TABLE "locations" ADD COLUMN "known_crag" text;