import { createHash } from 'node:crypto'

/**
 * The service worker, written at build time by the `wt6-service-worker` plugin
 * in `vite.config.ts` with the build's own file list baked in.
 *
 * **It keeps the app's own files on the device, and nothing else.** A cold
 * open used to download the page and its scripts before drawing anything; now
 * it draws from the device and the list (`rememberedLocations.ts`) at once,
 * and the weather loads as before. API calls go to another origin and are never
 * intercepted, so no weather, score or reading is ever served from here. The
 * Google Fonts stylesheet is left to the browser as well: the page's CSP gives
 * a worker no `connect-src` to reach it.
 *
 * It reverses an earlier "no service worker" decision, which turned down one
 * with nothing to cache; this one has the app shell to cache.
 *
 * **Updates arrive one open late.** A deploy changes the file list, so the
 * browser sees a new `sw.js` on the next open, installs it beside the running
 * page and deletes the old copy; the open after that draws the new build. The
 * running page is never swapped under the reader, and the app has no lazy
 * chunks for a deleted copy to strand.
 *
 * **Removing it takes a release, not a deletion.** A browser keeps a worker
 * whose script 404s. Retire it by shipping an `sw.js` that unregisters itself.
 */
export function renderServiceWorker(files: readonly string[], indexHtml: string): string {
  const precache = ['/index.html', ...files.map((f) => `/${f}`)].sort()
  const version = createHash('sha256')
    .update(indexHtml)
    .update(precache.join('\n'))
    .digest('hex')
    .slice(0, 12)

  return `// Generated by vite.config.ts from src/theme/serviceWorker.ts. Do not edit.
const CACHE = 'wt6-shell-${version}'
const PRECACHE = ${JSON.stringify(precache)}
const SHELL = new Set(PRECACHE)

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  // Every path is the one page (vercel.json rewrites them all to index.html).
  const key = request.mode === 'navigate' ? '/index.html' : url.pathname
  if (!SHELL.has(key)) return
  event.respondWith(
    caches.match(key, { cacheName: CACHE }).then((hit) => hit ?? fetch(request)),
  )
})
`
}

/** What goes in the shell: the hashed build output, never source maps. */
export function shellFiles(bundleFiles: readonly string[]): string[] {
  return bundleFiles.filter((f) => f.startsWith('assets/') && !f.endsWith('.map'))
}
